### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by ghost** [srose30206/prj-rev-bwfs-dasmoto#7]
https://github.com/srose30206/prj-rev-bwfs-dasmoto/blob/master/DasMoto/style.css#L1-L10

This is not readable.

Don't write your CSS rules on a single line. Always conform to this style convention:

```css
selector {
  property: value;
}

// or for a rule with multiple selectors

selector, selector { 
  property: value;
}
```
